nzp-team/quakec

source/shared/weapon_defines.qc
it was missing from `isPaPweaon`
=> SERVER: Fix m2Flame Pack a punch

source/server/entities/doors.qc
Fixed doors only targeting first target by removing the lines setting all the targets to the first one.
**Platforms tested**
PC - Confirmed by me and BCDeshiG
PSP - Confirmed by BCDeshiG
3DS - Confirmed by me
=> SERVER: Fixed doors only targeting first target

source/server/rounds.qc
The achievement should trigger at round 16 at the earliest after the description "Survive an entire Round without Perks past Round 15 or higher".
The achievement triggers at the end of round 12, regardless if you bought perks or not.
I added a line to check if it's after round 15 and removed the line "players.ach_tracker_npnp = 0;" which reset the count of drank perks, so it triggers correctly.
=> Fixed the achievement "No Perks? No Problem"

source/server/damage.qc
Added a reset for the tracker of the achievement when you get downed, so you can earn the achievement again.
=> Fixed the achievement "No Perks? No Problem" after getting downed

source/client/user_input.qc
Updating to SDL made some input boxes randomly break. This HACK seems to fix them to function correctly, at the cost of breaking shift. So now you can't type any capital letters. Too bad!
=> SDL input box hotfix HACK

source/server/damage.qc
DieHandler was adding these points anyway, and the amount it adds for grenades is not correct. It was also causing crashes when explosive barrel props killed zombies, because it wasn't properly guarded.
Fixes: https://github.com/nzp-team/nzportable/issues/783
=> Remove if statement adding points for explosive kills

source/client/main.qc
This is to stop the controller stick from being able to turn the camera while paused.
This also requires a separate FTE engine change, but should still be fine to merge here.
=> CLIENT: Set setsensitivityscaler to 0 while paused

progs/menu.src, source/client/defs/fte.qc, source/menu/defs/fte.qc, source/menu/defs/menu_defs.qc, source/menu/m_menu.qc, source/menu/menu_coop.qc, source/menu/menu_main.qc, source/menu/menu_maps.qc, source/menu/sui_sys.qc
Added:
- Co-Op menu tree, including the menus for changing the player's name, joining a game directly, browsing servers, and creating servers.
Bugs:
- SUI's builtin text input is a bit unfinished, I need to code in a way to cap the length to the size of the drawn box.
Unfinished:
- The server list needs better styling and also needs interactivity added, as well as sorting (maybe).
- I need to add the equivalent `Menu_*_GetNextButton` and `Menu_*_GetPreviousButton` functions for the Co-Op menus. I will probably do those last, though it will need special care to account for the server list.
- The "Create Game" menu doesn't properly create the server at the end of the options. The "Maps" menu might need to be edited slightly to account for this.
=> MENU: Co-Op Menus WIP + Server Browser

source/menu/menu_coop.qc
this doesn't affect our current in-repo build of FTEQCC, but newer builds of FTEQCC have been affected. this addresses https://github.com/nzp-team/quakec/issues/93
=> MENU: menu_coop.qc: fix macro syntax error

source/menu/menu_paus.qc
Fixes https://github.com/nzp-team/nzportable/issues/1047
It looks like the player count was changed from a 0 index to a 1 index, but this code was not updated.
=> CLIENT: Fix restart button being gray in solo

source/menu/menu_opts.qc
A tiny fix, but a nice one. Closes https://github.com/nzp-team/nzportable/issues/1082.
=> [MENU] Fix accessibility menu being inaccessible from gamepad / keyboard

source/server/weapons/weapon_core.qc
The previous logic added the whole reserve to the magazine, which could overfill magazines when the reserve didn't have enough to fill both guns
fixes https://github.com/nzp-team/nzportable/issues/1096
=> SERVER: Refactor W_Give_Ammo, ensure only the needed ammo gets added to the magazine

source/client/hud.qc
Fixes nzp-team/nzportable#1095.
=> Improved logic in HUD_AmmoString()

source/shared/weapon_stats.qc
The Gewehr 43's magazine size was swapped between its base and PaP variation - this fixes that.
Closes <https://github.com/nzp-team/nzportable/issues/1102>.
=> Fix incorrect mag size for Gewehr 43

source/server/damage.qc
The code assumed the IDs of the weapons would stay the same after one is removed. Instead, loop and call Weapon_RemoveWeapon(0).
The code would only remove one weapon when dying, this fixes that
I tested this when dying with one weapon, two weapons, and three weapons.
=> SERVER: Properly remove all weapons on game over

source/menu/menu_maps.qc
Add a button to the map selection menu that starts a random map
This PR adds a button that starts a random map 
Implements https://github.com/nzp-team/nzportable/issues/646
=> CLIENT: Add random map button

progs/ssqc.src, source/server/clientfuncs.qc, source/server/defs/standard.qc, source/server/player/player_core.qc, source/server/tests/test_module.qc, source/server/tests/test_perksacola.qc, source/server/tests/test_power.qc, source/server/utilities/game_restart.qc
---
Fixes the following Soft_Restart related problems and drafts unit tests to reproduce them:
* https://github.com/nzp-team/nzportable/issues/1116
* https://github.com/nzp-team/nzportable/issues/1125
* https://github.com/nzp-team/nzportable/issues/1126
---
See builds for passing unit tests
---
=> SERVER: Fix Perk and Power Switch related Restart issues

source/menu/menu_gpad.qc
---
Adds options for gamepad per-axis sensitivity to MenuQC.
---
---
=> MENU: Support GamePad sensitivity settings

progs/ssqc.src, source/server/tests/test_misc.qc, source/server/tests/test_module.qc, source/server/utilities/game_restart.qc
---
Fixes an issue where we would not stop the Game Over sequence if we restart the current level.
---
N/A
---
=> SERVER: Stop Game Over Sequence on Soft_Restart

source/client/hud.qc, source/client/main.qc, source/menu/main.qc, source/menu/menu_aces.qc
---
Adds a new setting in Accessibility to change player colors to be more friendly to people with CVD with increased contrast on the luma and minimal use of any red channels.
---
Before:
After:
---
=> CLIENT: Add accessibility setting for colorblind-safe(r) player colors

source/server/entities/wall_weapon.qc, source/shared/weapon_stats.qc
---
https://github.com/nzp-team/assets/pull/101 requires some changes to the frame counts for Bowie Knife playback, this implements that as well as adds support for the inspect sound.
---
https://github.com/user-attachments/assets/e195520e-bfa5-4f43-aa9c-39ca30108bac
---
- [x I have thoroughly tested my changes to the best of my ability
=> SERVER: Update frame calls for new Bowie Knife

source/shared/weapon_stats.qc
---
mg42 stopped doing damage this update, this fixes it, i also checked the mp40/mp5k and their pap-ed versions
---
before the fix:
https://github.com/user-attachments/assets/892bbd85-5a18-4f67-af5c-e778b6c0f5be
after the fix:
https://github.com/user-attachments/assets/0de541e4-9964-406d-9ecc-b104a9496163
---
=> SERVER: Fix MG42 not doing damage

source/server/gamemodes/gun_game.qc
---
This PR removes the flamethrower from the gun game weapon pool, and allows duplicates assuming they are not 2 slots within each other, since there's only 26 unique guns excluding the flamethrower.
The visual example is in solo play, but I also tested multiplayer, and did not notice any issues.
Closes https://github.com/nzp-team/nzportable/issues/1184
---
https://github.com/user-attachments/assets/b55efb91-4633-443c-92ed-8e25b6a3a877
---
=> SERVER: Fix flamethrower appearing in loot pool & allow duplicates assuming they are not 2 slots within each other

progs/ssqc.src, source/server/player/player_core.qc, source/server/tests/test_module.qc, source/server/tests/test_rounds.qc
---
Fixes an oversight where `PlayerSpawn` setting the round to `sv_startround` was ungated so would occur whenever a new client joined, or when a player respawned. Fixes https://github.com/nzp-team/nzportable/issues/1185
---
N/A
---
=> nzp-team/nzportable#1185 - Do not reset round state on PlayerSpawn

source/client/main.qc
---
The movement check for the crosshair was only picking up input when using keyboard controls (assuming default settings). This adds the movement flags to the left analog stick.
---
Tested on Windows with Xbox Series X Controller
Before:
https://github.com/user-attachments/assets/7a78570a-ebcd-475d-8146-959666de926b
After:
https://github.com/user-attachments/assets/17068d3c-9ff0-4718-9e50-c44392e6572b
---
=> CLIENT: Set movement flags for gamepad controls

source/server/weapons/weapon_core.qc
---
The fall damage formula previously always dealt the maximum damage of 98 due to the damage not being subtracted by 176 (the minimum fall damage distance)
This PR fixes that by using the height minus 176 when applying the damage formula.
---
In the previous behavior, a fall from any height over 176 dealt 98 damage, but in the new behavior, the damage scales by height.
(look top-left showing the damage after falling)
Previous behavior:
https://github.com/user-attachments/assets/b9e61a07-1b4d-4af8-adb0-32e2a88cd95b
New behavior:
https://github.com/user-attachments/assets/a293498a-d8db-45d6-9226-d6c37b85884a
---
=> SERVER: Fixed fall damage formula incorrectly dealing max damage at all distances

source/client/main.qc
---
Workaround for strange FTE behavior, runs `vid_reload` on a map reload as if we had new shaders to process to fix broken text rendering. Fixes nzp-team/nzportable#1252
---
N/A
---
=> nzp-team/nzportable#1252 - Always run `vid_reload` on WEB on world load
