source/shared/weapon_defines.qc
updated ADS/Frames for new model
=> Changes for new PPSH Model

source/shared/weapon_defines.qc
=> Changes to match new model

source/server/ai/ai_core.qc, source/server/ai/zombie_core.qc, source/server/main.qc
=> Fixing frames

source/server/ai/ai_core.qc, source/server/ai/crawler_core.qc, source/server/ai/zombie_core.qc, source/server/main.qc, source/server/weapons/weapon_core.qc
=> Updating zombie filepaths

source/shared/weapon_defines.qc
New model, animations, textures
=> MP40 Update

source/shared/defs/custom.qc, source/shared/weapon_defines.qc
adds all the coding for MP5K
to note, some things like the spread, recoil and kick are copied from the MP40, so they may be inaccurate, and might need to be changed in the future
=> Adding the MP5K

source/shared/weapon_defines.qc
new model weapon animations the whole 9 yards
=> STG-44-Update

source/shared/weapon_defines.qc
=> Updated frame counting

source/server/defs/quakespasm.qc, source/server/player.qc
Re-enabled traceline to enemy on Quakespasm
=> Added facingenemy def to Quakespasm

source/server/defs/quakespasm.qc
iframetime
bleed_out
Weapon_Name
=> Restored missing entity fields in QC

source/shared/weapon_defines.qc
ads values, animation frames, the whole 9 yards
=> Browning update code

source/shared/weapon_defines.qc
=> FG-42 update

source/shared/weapon_defines.qc
=> Panzer-update

source/server/weapons/weapon_core.qc, source/shared/defs/custom.qc, source/shared/weapon_defines.qc
code for springfield
as well as changing the kar sounds folder to Boltaction
=> Springfield

source/server/entities/triggers.qc
makes the correct world model load when placing the weapon
=> add world model loading

source/shared/weapon_defines.qc
updating the m2 fflamethrower code to match the new assets
=> SERVER: Update m2flamethrower

source/server/ai/zombie_core.qc, source/server/entities/powerups.qc, source/server/entities/window.qc, source/server/rounds.qc
Hoping to not have too many issues adding the stuff I did, but I (attempted to) fix the following issues:
**Bug: Powerups did not despawn their light on occassion**
Reported: No
**Bug: Co-op spawned too many zombies**
Reported: No
**Bug: Most window sounds were 2D**
Reported: No
**Bug: Zombies could melee during rising animtions** 
Reported: Issue #217 
The following fixes have only been tested on PC as I do not have access to any other platforms.
=> Fix multiple server-side issues

source/server/weapons/weapon_core.qc
Fixed an issue where if you sprinted and swapped weapons, your sprint anim would not continue to play.
=> Fix sprinting issue

source/shared/weapon_defines.qc
=> Mustang and sally update

source/shared/weapon_defines.qc
fixed some faces that were manually culled out before that should have been visible, as well as animation adjustments that save a small amount of RAM
=> Raygun culling and animation adjustments

source/server/entities/teleporter.qc
Uses zapper logic to kill zombies and create zap effect on death.
=> SERVER: Kill zombies during teleportation

source/shared/weapon_defines.qc
While playing I noticed most of the ironsights of the weapons were off.
I changed most of the weapons ADS values, so they are more accurate.
=> Update ADS positions

source/shared/weapon_defines.qc
Fixes [nzportable issue #651](https://github.com/nzp-team/nzportable/issues/651).
=> SERVER: Fix wunderwaffe reserve ammo

source/client/menu.qc
changing the text in the server creation process to make it unmistakable that it's optional
=> CLIENT: Change password text

source/server/weapons/bouncing_betty.qc, source/server/weapons/frames_core.qc
Changing the frames and sound timing for the new betty model and animation
=> SERVER: Bouncing betty update

source/client/user_input.qc
This reverts commit 07f630928bceb923b8209e11f50d7c6fdf80ef05.
No longer needed with:
https://github.com/nzp-team/fteqw/pull/3
=> Revert "SDL input box hotfix HACK"

source/server/utilities/weapon_utilities.qc
This broke buying weapons on standard.
=> SERVER/STANDARD: revert part of PR #73

source/server/entities/machines.qc
The entire switch statement could be replaced with one line
=> SERVER: Simplify logic of GivePerk

source/client/hud.qc
Fixes: https://github.com/nzp-team/nzportable/issues/989
=> CLIENT: Draw controller glyphs properly for bouncing betties prompt

source/menu/main.qc
this addresses https://github.com/nzp-team/nzportable/issues/998
=> MENU: fix console not opening in menu

source/client/hud.qc, source/server/damage.qc
Fixes https://github.com/nzp-team/nzportable/issues/1042
=> CLIENT: Don't draw hud if the game is over

.github/pull_request_template.md
---
Adds a PR template to the QuakeC repository.
---
You're seeing it right now!
---
=> GIT: Add Pull Request Template

.github/workflows/unit-tests.yml, progs/ssqc.src, source/server/defs/custom.qc, source/server/entities/mystery_box.qc, source/server/entities/perk_a_cola.qc, source/server/main.qc, source/server/player/player_core.qc, source/server/rounds.qc, source/server/tests/test_ai.qc, source/server/tests/test_math.qc, source/server/tests/test_misc_model.qc, source/server/tests/test_module.qc, source/server/tests/test_perksacola.qc, source/server/tests/test_score.qc, source/server/tests/test_weapons.qc, testing/run_unit_tests.sh, tools/qc-compiler-gnu.sh
---
Adds the infrastructure for unit testing our QuakeC server code. These unit tests are run during PR or can be run locally by using the compilation script with `--test-mode`. It provides a summary at end of test and supports basic assertions and skip functionality.
---
N/A, see builds.
---
=> SERVER/YML: Add Unit test infrastructure

progs/ssqc.src, source/server/clientfuncs.qc, source/server/defs/standard.qc, source/server/fte_builtins.qc
---
Minimal refactoring to introduce new strategy for unifying parts of FTE/Vril QuakeC via `fte_builtins`. This was meant to catch and reproduce https://github.com/nzp-team/nzportable/issues/1138 outside of Vril, but it's clear there is some greater issue that is difficult to triage. This PR mainly disables achievement functionality since there is no UX for it anyway, which will mitigate this problem for the time being. :(
---
---
=> SERVER: Introduce FTE reimplementation of Vril achievement builtin; early-out achievements

progs/ssqc.src, source/server/player/player_core.qc, source/server/utilities/weapon_utilities.qc, source/server/weapons/ballistic_knife.qc, source/server/weapons/frames_core.qc, source/server/weapons/weapon_core.qc, source/shared/shared_defs.qc, source/shared/weapon_stats.qc
---
Accommodates the Ballistic Knife model refresh as well as implements full functionality for knife projectiles, including reviving allies and the left hand holding a Bowie Knife if purchased.
---
---
=> SERVER: Ballistic Knife implementation
